# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/VirusTotal/vt-go
%global goipath         github.com/VirusTotal/vt-go
%global commit          8431ff2cc00f58def8a9e7de489c0e836d8b9d78

%gometa -f


%global common_description %{expand:
The official Go client library for VirusTotal API.}

%global golicenses      LICENSE
%global godocs          examples AUTHORS README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        The official Go client library for VirusTotal API

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
