# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/cavaliergopher/grab
%global owner cavaliergopher
%global project grab
%global goipath         github.com/cavaliercoder/grab
Version:                2.0.0
%global tag v2.0.0
%global commit 2c8601de6d9ac140430fd4c9de28509a0b855af5
%global shortcommit %(c=%{commit}; echo ${c:0:7})

%gometa -f


%global common_description %{expand:
A download manager package for Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A download manager package for Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         https://github.com/%{owner}/%{project}/archive/%{commit}/%{project}-%{shortcommit}.tar.gz

%description %{common_description}

%gopkg

%prep
%setup -q -n %{project}-%{shortcommit}
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
